import json
from decimal import Decimal
from pathlib import Path

#: Generated by scripts/build_tax_table.py from data/tax_rates.csv. Not committed,
#: so it exists only after that build step has run. Relative to the working
#: directory, which is the repo root in CI.
TABLE = Path("build/tax_rates.json")


def rate_for(state: str) -> Decimal:
    """Sales tax rate for a state, in percent."""
    rates = json.loads(TABLE.read_text(encoding="utf-8"))
    return Decimal(rates[state])
